name: Deploy to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Copy files to VM
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.GCP_VM_IP }}
            username: ${{ secrets.GCP_VM_USERNAME }}
            key: ${{ secrets.GCP_VM_SSH_KEY }}
            source: "."
            target: "/home/${{ secrets.GCP_VM_USERNAME }}/projects/task-management-bot"

        - name: SSH and Restart App
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.GCP_VM_IP }}
            username: ${{ secrets.GCP_VM_USERNAME }}
            key: ${{ secrets.GCP_VM_SSH_KEY }}
            script: |
              cd /home/${{ secrets.GCP_VM_USERNAME }}/projects/task-management-bot
              docker compose down
              docker compose up -d --build

